/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentBlogRouteImport } from './routes/agent-blog'
import { Route as AgentBlogIndexRouteImport } from './routes/agent-blog.index'
import { Route as AgentBlogArchiveRouteImport } from './routes/agent-blog.archive'
import { Route as AgentBlogAdminRouteImport } from './routes/agent-blog_.admin'
import { Route as AgentBlogEpisodesIndexRouteImport } from './routes/agent-blog.episodes.index'
import { Route as AgentBlogEpisodesIdRouteImport } from './routes/agent-blog.episodes.$id'
import { Route as AgentBlogReviewsIdRouteImport } from './routes/agent-blog.reviews.$id'
import { Route as AgentBlogAdminIndexRouteImport } from './routes/agent-blog_.admin.index'
import { Route as AgentBlogAdminEpisodesRouteImport } from './routes/agent-blog_.admin.episodes'
import { Route as AgentBlogAdminPublishedRouteImport } from './routes/agent-blog_.admin.published'
import { Route as AgentBlogAdminSettingsRouteImport } from './routes/agent-blog_.admin.settings'
import { Route as AgentBlogAdminReviewsIdRouteImport } from './routes/agent-blog_.admin.reviews.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentBlogRoute = AgentBlogRouteImport.update({
  id: '/agent-blog',
  path: '/agent-blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentBlogIndexRoute = AgentBlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AgentBlogRoute,
} as any)
const AgentBlogArchiveRoute = AgentBlogArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => AgentBlogRoute,
} as any)
const AgentBlogAdminRoute = AgentBlogAdminRouteImport.update({
  id: '/agent-blog_/admin',
  path: '/agent-blog/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentBlogEpisodesIndexRoute = AgentBlogEpisodesIndexRouteImport.update({
  id: '/episodes/',
  path: '/episodes/',
  getParentRoute: () => AgentBlogRoute,
} as any)
const AgentBlogEpisodesIdRoute = AgentBlogEpisodesIdRouteImport.update({
  id: '/episodes/$id',
  path: '/episodes/$id',
  getParentRoute: () => AgentBlogRoute,
} as any)
const AgentBlogReviewsIdRoute = AgentBlogReviewsIdRouteImport.update({
  id: '/reviews/$id',
  path: '/reviews/$id',
  getParentRoute: () => AgentBlogRoute,
} as any)
const AgentBlogAdminIndexRoute = AgentBlogAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AgentBlogAdminRoute,
} as any)
const AgentBlogAdminEpisodesRoute = AgentBlogAdminEpisodesRouteImport.update({
  id: '/episodes',
  path: '/episodes',
  getParentRoute: () => AgentBlogAdminRoute,
} as any)
const AgentBlogAdminPublishedRoute = AgentBlogAdminPublishedRouteImport.update({
  id: '/published',
  path: '/published',
  getParentRoute: () => AgentBlogAdminRoute,
} as any)
const AgentBlogAdminSettingsRoute = AgentBlogAdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AgentBlogAdminRoute,
} as any)
const AgentBlogAdminReviewsIdRoute = AgentBlogAdminReviewsIdRouteImport.update({
  id: '/reviews/$id',
  path: '/reviews/$id',
  getParentRoute: () => AgentBlogAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agent-blog': typeof AgentBlogRouteWithChildren
  '/agent-blog/archive': typeof AgentBlogArchiveRoute
  '/agent-blog/admin': typeof AgentBlogAdminRouteWithChildren
  '/agent-blog/': typeof AgentBlogIndexRoute
  '/agent-blog/episodes/$id': typeof AgentBlogEpisodesIdRoute
  '/agent-blog/reviews/$id': typeof AgentBlogReviewsIdRoute
  '/agent-blog/admin/episodes': typeof AgentBlogAdminEpisodesRoute
  '/agent-blog/admin/published': typeof AgentBlogAdminPublishedRoute
  '/agent-blog/admin/settings': typeof AgentBlogAdminSettingsRoute
  '/agent-blog/episodes/': typeof AgentBlogEpisodesIndexRoute
  '/agent-blog/admin/': typeof AgentBlogAdminIndexRoute
  '/agent-blog/admin/reviews/$id': typeof AgentBlogAdminReviewsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agent-blog/archive': typeof AgentBlogArchiveRoute
  '/agent-blog': typeof AgentBlogIndexRoute
  '/agent-blog/episodes/$id': typeof AgentBlogEpisodesIdRoute
  '/agent-blog/reviews/$id': typeof AgentBlogReviewsIdRoute
  '/agent-blog/admin/episodes': typeof AgentBlogAdminEpisodesRoute
  '/agent-blog/admin/published': typeof AgentBlogAdminPublishedRoute
  '/agent-blog/admin/settings': typeof AgentBlogAdminSettingsRoute
  '/agent-blog/episodes': typeof AgentBlogEpisodesIndexRoute
  '/agent-blog/admin': typeof AgentBlogAdminIndexRoute
  '/agent-blog/admin/reviews/$id': typeof AgentBlogAdminReviewsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agent-blog': typeof AgentBlogRouteWithChildren
  '/agent-blog/archive': typeof AgentBlogArchiveRoute
  '/agent-blog_/admin': typeof AgentBlogAdminRouteWithChildren
  '/agent-blog/': typeof AgentBlogIndexRoute
  '/agent-blog/episodes/$id': typeof AgentBlogEpisodesIdRoute
  '/agent-blog/reviews/$id': typeof AgentBlogReviewsIdRoute
  '/agent-blog_/admin/episodes': typeof AgentBlogAdminEpisodesRoute
  '/agent-blog_/admin/published': typeof AgentBlogAdminPublishedRoute
  '/agent-blog_/admin/settings': typeof AgentBlogAdminSettingsRoute
  '/agent-blog/episodes/': typeof AgentBlogEpisodesIndexRoute
  '/agent-blog_/admin/': typeof AgentBlogAdminIndexRoute
  '/agent-blog_/admin/reviews/$id': typeof AgentBlogAdminReviewsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agent-blog'
    | '/agent-blog/archive'
    | '/agent-blog/admin'
    | '/agent-blog/'
    | '/agent-blog/episodes/$id'
    | '/agent-blog/reviews/$id'
    | '/agent-blog/admin/episodes'
    | '/agent-blog/admin/published'
    | '/agent-blog/admin/settings'
    | '/agent-blog/episodes/'
    | '/agent-blog/admin/'
    | '/agent-blog/admin/reviews/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agent-blog/archive'
    | '/agent-blog'
    | '/agent-blog/episodes/$id'
    | '/agent-blog/reviews/$id'
    | '/agent-blog/admin/episodes'
    | '/agent-blog/admin/published'
    | '/agent-blog/admin/settings'
    | '/agent-blog/episodes'
    | '/agent-blog/admin'
    | '/agent-blog/admin/reviews/$id'
  id:
    | '__root__'
    | '/'
    | '/agent-blog'
    | '/agent-blog/archive'
    | '/agent-blog_/admin'
    | '/agent-blog/'
    | '/agent-blog/episodes/$id'
    | '/agent-blog/reviews/$id'
    | '/agent-blog_/admin/episodes'
    | '/agent-blog_/admin/published'
    | '/agent-blog_/admin/settings'
    | '/agent-blog/episodes/'
    | '/agent-blog_/admin/'
    | '/agent-blog_/admin/reviews/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentBlogRoute: typeof AgentBlogRouteWithChildren
  AgentBlogAdminRoute: typeof AgentBlogAdminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-blog': {
      id: '/agent-blog'
      path: '/agent-blog'
      fullPath: '/agent-blog'
      preLoaderRoute: typeof AgentBlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-blog/': {
      id: '/agent-blog/'
      path: '/'
      fullPath: '/agent-blog/'
      preLoaderRoute: typeof AgentBlogIndexRouteImport
      parentRoute: typeof AgentBlogRoute
    }
    '/agent-blog/archive': {
      id: '/agent-blog/archive'
      path: '/archive'
      fullPath: '/agent-blog/archive'
      preLoaderRoute: typeof AgentBlogArchiveRouteImport
      parentRoute: typeof AgentBlogRoute
    }
    '/agent-blog_/admin': {
      id: '/agent-blog_/admin'
      path: '/agent-blog/admin'
      fullPath: '/agent-blog/admin'
      preLoaderRoute: typeof AgentBlogAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-blog/episodes/': {
      id: '/agent-blog/episodes/'
      path: '/episodes'
      fullPath: '/agent-blog/episodes/'
      preLoaderRoute: typeof AgentBlogEpisodesIndexRouteImport
      parentRoute: typeof AgentBlogRoute
    }
    '/agent-blog/episodes/$id': {
      id: '/agent-blog/episodes/$id'
      path: '/episodes/$id'
      fullPath: '/agent-blog/episodes/$id'
      preLoaderRoute: typeof AgentBlogEpisodesIdRouteImport
      parentRoute: typeof AgentBlogRoute
    }
    '/agent-blog/reviews/$id': {
      id: '/agent-blog/reviews/$id'
      path: '/reviews/$id'
      fullPath: '/agent-blog/reviews/$id'
      preLoaderRoute: typeof AgentBlogReviewsIdRouteImport
      parentRoute: typeof AgentBlogRoute
    }
    '/agent-blog_/admin/': {
      id: '/agent-blog_/admin/'
      path: '/'
      fullPath: '/agent-blog/admin/'
      preLoaderRoute: typeof AgentBlogAdminIndexRouteImport
      parentRoute: typeof AgentBlogAdminRoute
    }
    '/agent-blog_/admin/episodes': {
      id: '/agent-blog_/admin/episodes'
      path: '/episodes'
      fullPath: '/agent-blog/admin/episodes'
      preLoaderRoute: typeof AgentBlogAdminEpisodesRouteImport
      parentRoute: typeof AgentBlogAdminRoute
    }
    '/agent-blog_/admin/published': {
      id: '/agent-blog_/admin/published'
      path: '/published'
      fullPath: '/agent-blog/admin/published'
      preLoaderRoute: typeof AgentBlogAdminPublishedRouteImport
      parentRoute: typeof AgentBlogAdminRoute
    }
    '/agent-blog_/admin/settings': {
      id: '/agent-blog_/admin/settings'
      path: '/settings'
      fullPath: '/agent-blog/admin/settings'
      preLoaderRoute: typeof AgentBlogAdminSettingsRouteImport
      parentRoute: typeof AgentBlogAdminRoute
    }
    '/agent-blog_/admin/reviews/$id': {
      id: '/agent-blog_/admin/reviews/$id'
      path: '/reviews/$id'
      fullPath: '/agent-blog/admin/reviews/$id'
      preLoaderRoute: typeof AgentBlogAdminReviewsIdRouteImport
      parentRoute: typeof AgentBlogAdminRoute
    }
  }
}

interface AgentBlogRouteChildren {
  AgentBlogArchiveRoute: typeof AgentBlogArchiveRoute
  AgentBlogIndexRoute: typeof AgentBlogIndexRoute
  AgentBlogEpisodesIdRoute: typeof AgentBlogEpisodesIdRoute
  AgentBlogReviewsIdRoute: typeof AgentBlogReviewsIdRoute
  AgentBlogEpisodesIndexRoute: typeof AgentBlogEpisodesIndexRoute
}

const AgentBlogRouteChildren: AgentBlogRouteChildren = {
  AgentBlogArchiveRoute: AgentBlogArchiveRoute,
  AgentBlogIndexRoute: AgentBlogIndexRoute,
  AgentBlogEpisodesIdRoute: AgentBlogEpisodesIdRoute,
  AgentBlogReviewsIdRoute: AgentBlogReviewsIdRoute,
  AgentBlogEpisodesIndexRoute: AgentBlogEpisodesIndexRoute,
}

const AgentBlogRouteWithChildren = AgentBlogRoute._addFileChildren(
  AgentBlogRouteChildren,
)

interface AgentBlogAdminRouteChildren {
  AgentBlogAdminEpisodesRoute: typeof AgentBlogAdminEpisodesRoute
  AgentBlogAdminPublishedRoute: typeof AgentBlogAdminPublishedRoute
  AgentBlogAdminSettingsRoute: typeof AgentBlogAdminSettingsRoute
  AgentBlogAdminIndexRoute: typeof AgentBlogAdminIndexRoute
  AgentBlogAdminReviewsIdRoute: typeof AgentBlogAdminReviewsIdRoute
}

const AgentBlogAdminRouteChildren: AgentBlogAdminRouteChildren = {
  AgentBlogAdminEpisodesRoute: AgentBlogAdminEpisodesRoute,
  AgentBlogAdminPublishedRoute: AgentBlogAdminPublishedRoute,
  AgentBlogAdminSettingsRoute: AgentBlogAdminSettingsRoute,
  AgentBlogAdminIndexRoute: AgentBlogAdminIndexRoute,
  AgentBlogAdminReviewsIdRoute: AgentBlogAdminReviewsIdRoute,
}

const AgentBlogAdminRouteWithChildren = AgentBlogAdminRoute._addFileChildren(
  AgentBlogAdminRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentBlogRoute: AgentBlogRouteWithChildren,
  AgentBlogAdminRoute: AgentBlogAdminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
