/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as PublicIndexRouteImport } from './routes/_public.index'
import { Route as PublicArchiveRouteImport } from './routes/_public.archive'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminEpisodesRouteImport } from './routes/admin.episodes'
import { Route as AdminPublishedRouteImport } from './routes/admin.published'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as PublicEpisodesIndexRouteImport } from './routes/_public.episodes.index'
import { Route as PublicEpisodesIdRouteImport } from './routes/_public.episodes.$id'
import { Route as PublicReviewsIndexRouteImport } from './routes/_public.reviews.index'
import { Route as PublicReviewsIdRouteImport } from './routes/_public.reviews.$id'
import { Route as AdminReviewsIdRouteImport } from './routes/admin.reviews.$id'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicArchiveRoute = PublicArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => PublicRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEpisodesRoute = AdminEpisodesRouteImport.update({
  id: '/episodes',
  path: '/episodes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPublishedRoute = AdminPublishedRouteImport.update({
  id: '/published',
  path: '/published',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const PublicEpisodesIndexRoute = PublicEpisodesIndexRouteImport.update({
  id: '/episodes/',
  path: '/episodes/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicEpisodesIdRoute = PublicEpisodesIdRouteImport.update({
  id: '/episodes/$id',
  path: '/episodes/$id',
  getParentRoute: () => PublicRoute,
} as any)
const PublicReviewsIndexRoute = PublicReviewsIndexRouteImport.update({
  id: '/reviews/',
  path: '/reviews/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicReviewsIdRoute = PublicReviewsIdRouteImport.update({
  id: '/reviews/$id',
  path: '/reviews/$id',
  getParentRoute: () => PublicRoute,
} as any)
const AdminReviewsIdRoute = AdminReviewsIdRouteImport.update({
  id: '/reviews/$id',
  path: '/reviews/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/archive': typeof PublicArchiveRoute
  '/admin/episodes': typeof AdminEpisodesRoute
  '/admin/published': typeof AdminPublishedRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/episodes/$id': typeof PublicEpisodesIdRoute
  '/reviews/$id': typeof PublicReviewsIdRoute
  '/admin/reviews/$id': typeof AdminReviewsIdRoute
  '/episodes/': typeof PublicEpisodesIndexRoute
  '/reviews/': typeof PublicReviewsIndexRoute
}
export interface FileRoutesByTo {
  '/archive': typeof PublicArchiveRoute
  '/admin/episodes': typeof AdminEpisodesRoute
  '/admin/published': typeof AdminPublishedRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminIndexRoute
  '/episodes/$id': typeof PublicEpisodesIdRoute
  '/reviews/$id': typeof PublicReviewsIdRoute
  '/admin/reviews/$id': typeof AdminReviewsIdRoute
  '/episodes': typeof PublicEpisodesIndexRoute
  '/reviews': typeof PublicReviewsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/_public/archive': typeof PublicArchiveRoute
  '/admin/episodes': typeof AdminEpisodesRoute
  '/admin/published': typeof AdminPublishedRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/_public/': typeof PublicIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/_public/episodes/$id': typeof PublicEpisodesIdRoute
  '/_public/reviews/$id': typeof PublicReviewsIdRoute
  '/admin/reviews/$id': typeof AdminReviewsIdRoute
  '/_public/episodes/': typeof PublicEpisodesIndexRoute
  '/_public/reviews/': typeof PublicReviewsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/archive'
    | '/admin/episodes'
    | '/admin/published'
    | '/admin/settings'
    | '/admin/'
    | '/episodes/$id'
    | '/reviews/$id'
    | '/admin/reviews/$id'
    | '/episodes/'
    | '/reviews/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/archive'
    | '/admin/episodes'
    | '/admin/published'
    | '/admin/settings'
    | '/'
    | '/admin'
    | '/episodes/$id'
    | '/reviews/$id'
    | '/admin/reviews/$id'
    | '/episodes'
    | '/reviews'
  id:
    | '__root__'
    | '/_public'
    | '/admin'
    | '/_public/archive'
    | '/admin/episodes'
    | '/admin/published'
    | '/admin/settings'
    | '/_public/'
    | '/admin/'
    | '/_public/episodes/$id'
    | '/_public/reviews/$id'
    | '/admin/reviews/$id'
    | '/_public/episodes/'
    | '/_public/reviews/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicRoute: typeof PublicRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/archive': {
      id: '/_public/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof PublicArchiveRouteImport
      parentRoute: typeof PublicRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/episodes': {
      id: '/admin/episodes'
      path: '/episodes'
      fullPath: '/admin/episodes'
      preLoaderRoute: typeof AdminEpisodesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/published': {
      id: '/admin/published'
      path: '/published'
      fullPath: '/admin/published'
      preLoaderRoute: typeof AdminPublishedRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_public/episodes/': {
      id: '/_public/episodes/'
      path: '/episodes'
      fullPath: '/episodes/'
      preLoaderRoute: typeof PublicEpisodesIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/episodes/$id': {
      id: '/_public/episodes/$id'
      path: '/episodes/$id'
      fullPath: '/episodes/$id'
      preLoaderRoute: typeof PublicEpisodesIdRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/reviews/': {
      id: '/_public/reviews/'
      path: '/reviews'
      fullPath: '/reviews/'
      preLoaderRoute: typeof PublicReviewsIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/reviews/$id': {
      id: '/_public/reviews/$id'
      path: '/reviews/$id'
      fullPath: '/reviews/$id'
      preLoaderRoute: typeof PublicReviewsIdRouteImport
      parentRoute: typeof PublicRoute
    }
    '/admin/reviews/$id': {
      id: '/admin/reviews/$id'
      path: '/reviews/$id'
      fullPath: '/admin/reviews/$id'
      preLoaderRoute: typeof AdminReviewsIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface PublicRouteChildren {
  PublicArchiveRoute: typeof PublicArchiveRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicEpisodesIdRoute: typeof PublicEpisodesIdRoute
  PublicReviewsIdRoute: typeof PublicReviewsIdRoute
  PublicEpisodesIndexRoute: typeof PublicEpisodesIndexRoute
  PublicReviewsIndexRoute: typeof PublicReviewsIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicArchiveRoute: PublicArchiveRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicEpisodesIdRoute: PublicEpisodesIdRoute,
  PublicReviewsIdRoute: PublicReviewsIdRoute,
  PublicEpisodesIndexRoute: PublicEpisodesIndexRoute,
  PublicReviewsIndexRoute: PublicReviewsIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

interface AdminRouteChildren {
  AdminEpisodesRoute: typeof AdminEpisodesRoute
  AdminPublishedRoute: typeof AdminPublishedRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminReviewsIdRoute: typeof AdminReviewsIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminEpisodesRoute: AdminEpisodesRoute,
  AdminPublishedRoute: AdminPublishedRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminReviewsIdRoute: AdminReviewsIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PublicRoute: PublicRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
