import { useState } from 'react';
import { createFileRoute, Link, Outlet } from '@tanstack/react-router';
import { AudioLines, Rss, Search, Menu, ArrowUpRight } from 'lucide-react';
import { PersistentPlayer } from '../features/public/player/provider';
import { BottomSheet } from '../features/public/beui/bottom-sheet';
import { Button } from '../features/public/beui/button';
import { siteConfig } from '../site';
import { text } from '../features/public/locale';
import '../features/public/public.css';
export const Route = createFileRoute('/_public')({ component: PublicLayout });
function PublicLayout() {
  const [panel, setPanel] = useState<'menu' | 'subscribe'>('menu');
  const [panelOpen, setPanelOpen] = useState(false);
  const openPanel = (next: 'menu' | 'subscribe') => { setPanel(next); setPanelOpen(true); };
  const navigation = <><Link to="/" activeOptions={{ exact: true }} activeProps={{ className: 'is-active' }} onClick={() => setPanelOpen(false)}>{text('首页', 'Home')}</Link><Link to="/episodes" activeOptions={{ exact: false }} activeProps={{ className: 'is-active' }} onClick={() => setPanelOpen(false)}>{siteConfig.nav.episodes}</Link><Link to="/reviews" activeProps={{ className: 'is-active' }} onClick={() => setPanelOpen(false)}>{siteConfig.nav.latest}</Link><Link to="/archive" search={{ type: 'all', q: '', month: '' }} activeOptions={{ includeSearch: false }} activeProps={{ className: 'is-active' }} onClick={() => setPanelOpen(false)}>{siteConfig.nav.archive}</Link></>;
  return <div className="public-site"><header className="public-header"><div className="public-header-inner"><Link to="/" className="public-brand"><span className="brand-mark"><AudioLines size={22} aria-hidden="true" /></span><span>{siteConfig.title}<small>{text('听见新想法，读懂新进展', 'New ideas. Meaningful progress.')}</small></span></Link><nav className="public-nav" aria-label={siteConfig.nav.label}>{navigation}</nav><div className="header-actions"><Link to="/archive" search={{ type: 'all', q: '', month: '' }} className="header-search" aria-label={text('搜索公开内容', 'Search published content')}><Search size={19} aria-hidden="true" /></Link><Button variant="outline" className="subscribe-button" aria-expanded={panelOpen && panel === 'subscribe'} aria-haspopup="dialog" onClick={() => openPanel('subscribe')}><Rss size={15} aria-hidden="true" />{text('订阅', 'Subscribe')}</Button><Button variant="ghost" size="icon" className="mobile-menu-button" aria-expanded={panelOpen && panel === 'menu'} aria-haspopup="dialog" onClick={() => openPanel('menu')} aria-label={text('打开导航菜单', 'Open navigation menu')}><Menu size={22} aria-hidden="true" /></Button></div></div></header><main className="public-main"><Outlet /></main><footer className="public-footer"><div><Link to="/" className="footer-brand">{siteConfig.title}</Link><p>{siteConfig.tagline}</p></div><div className="footer-links"><a href="/episodes/rss.xml">{siteConfig.episodes.subscribe}<ArrowUpRight size={14} aria-hidden="true" /></a><a href="/rss.xml">{text('订阅全部内容', 'Subscribe to all content')}<ArrowUpRight size={14} aria-hidden="true" /></a></div><p className="footer-note">{text('持续记录，慢慢读。', 'Made for listening. Made for reading.')}</p></footer><PersistentPlayer /><BottomSheet open={panelOpen} onOpenChange={setPanelOpen} title={panel === 'subscribe' ? text('选择订阅', 'Choose a feed') : siteConfig.nav.label} snapPoints={['auto']} className="public-site public-navigation-sheet">{panel === 'menu' ? <nav className="mobile-nav" aria-label={siteConfig.nav.label}>{navigation}<Button variant="outline" className="mobile-nav-subscribe" onClick={() => openPanel("subscribe")}><Rss size={16} aria-hidden="true" />{text("订阅", "Subscribe")}</Button></nav> : <div className="subscription-options"><a href="/episodes/rss.xml"><Rss size={21} /><span><strong>{siteConfig.episodes.subscribe}</strong><small>{siteConfig.episodes.description}</small></span><ArrowUpRight size={18} /></a><a href="/rss.xml"><Rss size={21} /><span><strong>{text('订阅全部内容', 'All published content')}</strong><small>{text('早咖啡与工作日志，一个 RSS 入口。', 'Morning Coffee and worklogs in one feed.')}</small></span><ArrowUpRight size={18} /></a></div>}</BottomSheet></div>;
}
