import preferences from "@/blog.config.json";
import { resolveTheme } from "@/themes/registry";

const language = preferences.language === "zh-CN" ? "zh-CN" : "en";
export const activeTheme = resolveTheme(preferences.theme);

const translations = {
  en: {
    title: "Night Shift",
    eyebrow: "An agent worklog",
    description:
      "Selected, publication-safe notes from the work agents completed while people were away.",
    nav: { label: "Primary navigation", latest: "Latest", archive: "Archive", rss: "RSS" },
    footer: {
      reporting: "Reporting from",
      disclaimer: "Reported outcomes, reviewed by a human before publication.",
    },
    home: {
      kicker: "Machine work, human edited",
      heading: "The work that",
      headingEmphasis: "survived the night.",
      policyLabel: "Editorial policy",
      note: "PUBLICATION NOTE / 001",
      policy: "Not every action deserves a post. We publish only the work that changed the state of a project.",
      input: "Input",
      inputValue: "Visible messages",
      filter: "Filter",
      filterValue: "Publication-safe",
      gate: "Gate",
      gateValue: "Human approval",
      ticker: ["NO CHAIN OF THOUGHT", "NO RAW TRANSCRIPTS", "NO EMPTY UPDATES"],
      latest: "Latest dispatch",
      reviewed: "Reviewed / published",
      configured: "The night shift is configured.",
      empty: "No important update has cleared review yet.",
      previous: "Previous reports",
      fullArchive: "Full archive →",
    },
    archive: {
      title: "Archive",
      description: "Every human-approved Daily Review, in chronological order.",
      kicker: "The record",
      publishedReviews: "Published reviews",
      summary: (count: number) => `${count} reviewed dispatch${count === 1 ? "" : "es"}. No raw logs. No filler.`,
    },
    review: {
      read: "Read",
      signals: "signals",
      open: "Open report",
      back: "Back to latest reviews",
      latest: "Latest",
      daily: "Daily review",
      report: "REPORT",
      day: "Review day",
      source: "Source",
      status: "Status",
      approved: "Human approved",
      disclaimer: "This report describes outcomes stated in visible messages. It is not an execution audit.",
      continue: "Continue through the archive →",
    },
  },
  "zh-CN": {
    title: "夜班日志",
    eyebrow: "Agent 工作纪要",
    description: "从 Agent 已完成的工作中，筛选值得公开且通过隐私检查的重要进展。",
    nav: { label: "主导航", latest: "最新", archive: "归档", rss: "RSS" },
    footer: {
      reporting: "报告来源",
      disclaimer: "内容由 Agent 总结，并在发布前经过人工审核。",
    },
    home: {
      kicker: "机器执行，人工编辑",
      heading: "留下真正",
      headingEmphasis: "改变进度的工作。",
      policyLabel: "编辑原则",
      note: "发布说明 / 001",
      policy: "不是每次操作都值得发布。这里只记录真正改变项目状态的重要工作。",
      input: "输入",
      inputValue: "可见消息",
      filter: "过滤",
      filterValue: "公开安全",
      gate: "发布门槛",
      gateValue: "人工批准",
      ticker: ["不读取思考过程", "不公开原始对话", "不发布空洞更新"],
      latest: "最新报告",
      reviewed: "已审核 / 已发布",
      configured: "夜班日志已配置完成。",
      empty: "还没有重要更新通过审核。",
      previous: "往期报告",
      fullArchive: "查看完整归档 →",
    },
    archive: {
      title: "归档",
      description: "按时间查看所有经过人工批准的每日工作报告。",
      kicker: "工作记录",
      publishedReviews: "已发布报告",
      summary: (count: number) => `${count} 篇已审核报告。不公开原始日志，不填充无效内容。`,
    },
    review: {
      read: "阅读",
      signals: "项进展",
      open: "打开报告",
      back: "返回最新报告",
      latest: "最新",
      daily: "每日报告",
      report: "报告",
      day: "报告日期",
      source: "来源",
      status: "状态",
      approved: "人工已批准",
      disclaimer: "本报告描述可见消息中陈述的结果，不构成完整的执行审计。",
      continue: "继续浏览归档 →",
    },
  },
} as const;

const localized = translations[language];

export const siteConfig = {
  theme: activeTheme.id,
  language,
  locale: language,
  sourceLabel: "OpenClaw / Gateway 01",
  ...localized,
  home: localized.home,
};
